apiVersion: v1
kind: Service
metadata:
    name: "testmoon-50ea"
    labels:
        app: "testmoon-50ea"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testmoon-50ea"